[package]
name = "font-awesome-embed-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Proc macros for font-awesome-embed"

[lib]
proc-macro = true

[features]
test-icons = ["font-awesome-embed-core/test-icons"]

[dependencies]
font-awesome-embed-core = { path = "../font-awesome-embed-core" }
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
