[package]
name = "font-awesome-embed-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Proc macros for font-awesome-embed"

[lib]
proc-macro = true

[features]
test-icons = []

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
ureq = { version = "3", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
